# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# hycom_MB.py
# Created on: 2015-09-14 16:40:55.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("C:/Program Files/GeoEco/ArcGISToolbox/Marine Geospatial Ecology Tools.tbx")


# Local variables:
save_workspace = "F:\\Remote Sensing Data\\HYCOM_GLBu0.08"
HYCOM_GLBu0_08__2_ = save_workspace
Scripts = "C:\\Program Files\\GeoEco\\ArcGISToolbox\\Scripts"

# 01. Process: Create Climatological Rasters for HYCOM GLBa0.08 Equatorial 4D Variable
arcpy.HYCOMGLBa008Equatorial4DCreateClimatologicalArcGISRasters_GeoEco("u", "Mean", "Monthly", save_workspace, "add", "%(VariableName)s;%(ClimatologyBinType)s_Climatology;Depth_%(Depth)04.0fm;%(VariableName)s_%(Depth)04.0fm_%(ClimatologyBinName)s_%(Statistic)s.img", "1", "1", "", "false", "-76 35 -69 42", "Degrees", "0", "0", "1/1/2002", "", "60", "120", "", "true", "false")

